In [ ]:
import zipfile
import pathlib

def unzip(path):
    path_list = path.rglob('*.zip')
    for paths in (path_list):
        with zipfile.ZipFile(paths, 'r') as zip_ref:
            zip_ref.extractall(str(paths)[:-4])
            os.remove(str(zip_ref))

In [ ]:
unzip('C:/Users/User/document/etc study/cj ai 해커톤/01.데이터')

In [48]:
# x_train 
def to_dataframe(path):
    path_list = path.rglob('Training/01.원천데이터/*')
    df_columns =[]
    for paths in path_list:
        json_path = paths.glob('*.json')
        for j in json_path:
            with open(j,encoding='utf-8') as json_file:
                data = json.load(json_file)['sourceDataInfo']
                df_columns.append(data) 
    df = pd.DataFrame(df_columns)
    return df


df = to_dataframe(Path('./01.데이터'))  
df.to_csv('X_train.csv')

In [44]:
# x_val 
def to_dataframe(path):
    path_list = path.rglob('Validation/01.원천데이터/*')
    df_columns =[]
    for paths in path_list:
        json_path = paths.glob('*.json')
        for j in json_path:
            with open(j,encoding='utf-8') as json_file:
                data = json.load(json_file)['sourceDataInfo']
                df_columns.append(data) 
    df = pd.DataFrame(df_columns)
    return df


df2 = to_dataframe(Path('./01.데이터'))  
df2.to_csv('X_Val.csv')

,newsID,newsCategory,newsSubcategory,newsTitle,newsSubTitle,newsContent,partNum,useType,processType,processPattern,processLevel,sentenceCount,sentenceInfo,processSentencenum
0,EC_M05_254060,경제,자동차,"울산이냐, 화성이냐…전기차 수출 1위 두고 엎치락뒤치락","현대차·기아, 전기차 수출 1위 주도권경쟁 기아, 화성공장 기반으로 수출 늘리며 가...",전기차 수출 전초기지를 두고 현대차와 기아 간 주도권 경쟁이 한층 치열해지고 있다....,P1,1,A,00,하,23,"[{'sentenceNo': 1, 'sentenceContent': '전기차 수출 ...",NaN
1,EC_M05_254082,경제,기업CEO,"LS전선아시아, 베트남 최대 이통사업자에 광케이블 공급",베트남·북미 수요 증가…케이블설비 '풀 가동',LS전선아시아는 베트남 호찌민시 소재 자회사인 LSCV가 베트남 최대 이동통신사업자...,P1,1,A,00,하,9,"[{'sentenceNo': 1, 'sentenceContent': 'LS전선아시아...",NaN
2,EC_M05_254091,경제,경제일반,"[6·21 부동산 대책]추경호 \""생애최초 주택구입시 200만원 내 취득세 면제\""...",제1차 부동산 관계장관회의,"추경호 경제부총리 겸 기획재정부 장관은 21일 \""생애최초 주택 구입시 소득·가격 ...",P1,1,A,00,하,8,"[{'sentenceNo': 1, 'sentenceContent': '추경호 경제부...",NaN
3,EC_M05_254095,경제,자동차,'현대 블루 프라이즈 디자인 2022' 최종 수상자에 '박지민',,현대자동차는 ‘현대 블루 프라이즈 디자인 2022’ 최종 수상자로 박지민 씨를 선정...,P1,1,A,00,하,14,"[{'sentenceNo': 1, 'sentenceContent': '현대자동차는 ...",NaN
4,EC_M05_254097,경제,유통,"일동후디스, '아이얌 웨하스' 실속형 대용량팩 출시",,일동후디스가 가격은 낮추고 용량은 늘린 온라인 전용 ‘아이얌 웨하스’ 실속형 대용량...,P1,1,A,00,하,8,"[{'sentenceNo': 1, 'sentenceContent': '일동후디스가 ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53622,SO_M07_920295,사회,사회일반,"경찰 \""수사권 조정안, 추가 후퇴 우려\""…檢·警 수장 국회서 맞붙나",null,경찰 내부에서 수사권 조정안 후퇴에 대한 우려가 새어 나오고 있다.\n문무일 검찰총...,P2,1,A,00,하,18,"[{'sentenceNo': 1, 'sentenceContent': '경찰 내부에서...",0.0
53623,SO_M07_920298,사회,전국,제주4.3 추념식 봉행 “특별법 개정…4.3 완전 해결 첫 걸음“,이낙연 총리 “4·3의 진실 채우고 명예를 회복해 드리겠다” 도올 김용옥·배우 유아...,[제주=파이낸셜뉴스] 좌승훈 기자=제71주년 제주4·3 희생자 추념식이 3일 오전 ...,P2,1,A,00,하,11,"[{'sentenceNo': 1, 'sentenceContent': '[제주=파이낸...",0.0
53624,SO_M07_920301,사회,전국,[전통시장과 함께하는 재래夜 놀자] 밤이 즐거운 서문시장 夜시장,대구 서문시장 야시장 먹거리·볼거리 어우러진 국내 최대 규모 야시장 누적방문객 2천...,"\""대구 서문시장 야시장에서 야(夜)하게 놀자!\"" 지난 2016년 6월 국내 최대...",P2,1,A,00,하,28,"[{'sentenceNo': 1, 'sentenceContent': '\""대구 서문...",0.0
53625,SO_M07_920305,사회,전국,"충남도, 단지·개별형 외국인투자지역 ‘전국 1위’",6곳 142만 8000㎡·19곳 83만 1000㎡…‘외국인 투자 최적지’ 입증,충남도가 단지형과 개별형 외국인투자지역을 전국에서 가장 많이 보유하고 있는 것으로 ...,P2,1,A,00,하,9,"[{'sentenceNo': 1, 'sentenceContent': '충남도가 단지...",0.0
53626,SO_M07_920312,사회,전국,경남 ‘고용위기지역’ 1년 연장..경제 활력 회복 계기 마련,"창원시 진해구·통영시·거제시·고성군, 2020년 4월 4일까지 고용안정 및 일자리사...",지난해 정부로부터 1년간 고용위기지역으로 지정된 경남지역 4개 시군의 고용위기지역 ...,P2,1,A,00,하,9,"[{'sentenceNo': 1, 'sentenceContent': '지난해 정부로...",0.0

In [11]:
def to_dataframe(path):
    path_list = path.rglob('Training/02.라벨링데이터/*')
    df_columns =[]
    for paths in path_list:
        json_path = paths.glob('*.json')
        for j in json_path:
            with open(j,encoding='utf-8') as json_file:
                data = json.load(json_file)['labeledDataInfo']
                df_columns.append(data) 
    df = pd.DataFrame(df_columns)
    return df


df3 = to_dataframe(Path('./01.데이터'))  
df3.to_csv('y_train.csv')

In [ ]:
from pathlib import Path
import pathlib
import json
import pandas as pd

def to_dataframe(path):
    path_list = path.rglob('Validation/02.라벨링데이터/*')
    df_columns =[]
    for paths in path_list:
        json_path = paths.glob('*.json')
        for j in json_path:
            with open(j,encoding='utf-8') as json_file:
                data = json.load(json_file)['labeledDataInfo']
                df_columns.append(data) 
    df = pd.DataFrame(df_columns)
    return df


df4 = to_dataframe(Path('./01.데이터'))  
df4
df4.to_csv('y_Val.csv')

In [ ]:
data = data[['newsCategory','newsSubcategory','newsTitle','newsTitle','newsContent']] # 사용할 주요 column
data

,newsCategory,newsSubcategory,newsTitle,newsTitle,newsContent
0,경제,중기밴처,CCTV 영상으로 핫해진 에스원,CCTV 영상으로 핫해진 에스원,"#. 서울의 한 카페, 아르바이트생이 마감 청소 중 춤을 추고 있다.\n춤 솜씨가 ..."
1,경제,유통,"홈플러스, 신년 '반값, 하나 더 데이' 행사…하루 빠른 31일 시작","홈플러스, 신년 '반값, 하나 더 데이' 행사…하루 빠른 31일 시작","홈플러스는 새해 첫 쇼핑 축제 '반값, 하나 더 데이' 행사를 경쟁사 대비 하루 빠..."
2,경제,유통,"제주삼다수, 글로벌 품질 인증 갱신","제주삼다수, 글로벌 품질 인증 갱신",제주특별자치도개발공사는 제주삼다수의 품질경영표준 ISO9001을 갱신함과 동시에 미...
3,경제,기업CEO,"SK하이닉스, 인텔 낸드 인수 1단계 완료…美자회사 이름은 '솔리다임'","SK하이닉스, 인텔 낸드 인수 1단계 완료…美자회사 이름은 '솔리다임'",SK하이닉스가 미국 인텔의 낸드플래시 사업부 인수 1단계 절차를 완료하고 인텔 SS...
4,경제,경제일반,"홍남기 \""항만사용료 감면 6개월 더\""…코로나 장기화에 한시조치 줄줄이 연장(상보)","홍남기 \""항만사용료 감면 6개월 더\""…코로나 장기화에 한시조치 줄줄이 연장(상보)",정부가 당초 올해 말까지 시행하려던 항만사용료 및 터미널 임대료 감면조치를 내년 6...
...,...,...,...,...,...
429117,사회,"사회,사회일반,사회일반","롯데마트, 하이엔드 한우브랜드 ‘마블나인’ 출시…청담에서 오마카세로 첫선","롯데마트, 하이엔드 한우브랜드 ‘마블나인’ 출시…청담에서 오마카세로 첫선",올해 4월 시그니처 와인 출시 기념으로 동묘에 와인바를 선보였던 롯데마트가 이번에는...
429118,사회,"사회,사건사고,사건사고","검찰, 치킨·삼계탕용 닭고기 가격 담합 하림 등 6개사 불구속 기소","검찰, 치킨·삼계탕용 닭고기 가격 담합 하림 등 6개사 불구속 기소",하림 등 닭고기 업체들이 치킨용 닭고기 값을 장기간 ‘짬짜미’한 혐의로 재판에 넘겨...
429119,사회,"사회,사건사고,사건사고","경찰청, 112치안종합상황실 리모델링…\""AI 등 첨단 장비 탑재\""","경찰청, 112치안종합상황실 리모델링…\""AI 등 첨단 장비 탑재\""",경찰이 112치안종합상황실을 인공지능(AI) 등 첨단 장비가 탑재된 공간으로 재설계...
429120,사회,"사회,사회일반,사회일반","신세계百 강남점, 보테가 베네타 신상품 국내 최초 공개…럭셔리 랜드마크 주목","신세계百 강남점, 보테가 베네타 신상품 국내 최초 공개…럭셔리 랜드마크 주목",지난해 약 10개월간 리뉴얼을 통해 새롭게 단장한 신세계(004170)백화점 강남점...
429121,사회,"사회,사회일반,사회일반",인천 ‘그 갯벌’에 차량 또 빠졌다…이달만 벌써 3번째,인천 ‘그 갯벌’에 차량 또 빠졌다…이달만 벌써 3번째,최근 전기차와 억대 SUV(스포츠유틸리티) 차량이 연이어 빠졌던 인천 옹진군 선재도...

In [1]:
import pandas as pd
x_train = pd.read_csv('X_train.csv')
x_val = pd.read_csv('X_Val.csv')
y_train = pd.read_csv('y_train.csv')
y_Val = pd.read_csv('y_Val.csv')
x_train.shape , x_val.shape , y_train.shape , y_Val.shape

C:\Users\User\AppData\Local\Temp\ipykernel_1796\1088936973.py:4: DtypeWarning: Columns (1,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  y_train = pd.read_csv('y_train.csv')

((429122, 15), (53627, 15), (586724, 5), (73321, 5))

In [3]:
df = pd.read_csv('df_concat.csv')
df

,Unnamed: 0.1,Unnamed: 0,newsID,newsCategory,newsSubcategory,newsTitle,newsSubTitle,newsContent,partNum,useType,processType,processPattern,processLevel,sentenceCount,sentenceInfo,processSentencenum
0,0,0,EC_M05_241847,경제,중기밴처,CCTV 영상으로 핫해진 에스원,"에스원 자체 제작 영상, 유튜브·틱톡 조회수 3500만회 돌파 유튜버들과 협업한 콘...","#. 서울의 한 카페, 아르바이트생이 마감 청소 중 춤을 추고 있다.\n춤 솜씨가 ...",P1,1,A,0,하,15,"[{'sentenceNo': 1, 'sentenceContent': '#. 서울의 ...",NaN
1,1,1,EC_M05_241848,경제,유통,"홈플러스, 신년 '반값, 하나 더 데이' 행사…하루 빠른 31일 시작",NaN,"홈플러스는 새해 첫 쇼핑 축제 '반값, 하나 더 데이' 행사를 경쟁사 대비 하루 빠...",P1,1,A,0,하,8,"[{'sentenceNo': 1, 'sentenceContent': ""홈플러스는 새...",NaN
2,2,2,EC_M05_241851,경제,유통,"제주삼다수, 글로벌 품질 인증 갱신",NaN,제주특별자치도개발공사는 제주삼다수의 품질경영표준 ISO9001을 갱신함과 동시에 미...,P1,1,A,0,하,6,"[{'sentenceNo': 1, 'sentenceContent': '제주특별자치도...",NaN
3,3,3,EC_M05_241852,경제,기업CEO,"SK하이닉스, 인텔 낸드 인수 1단계 완료…美자회사 이름은 '솔리다임'",NaN,SK하이닉스가 미국 인텔의 낸드플래시 사업부 인수 1단계 절차를 완료하고 인텔 SS...,P1,1,A,0,하,13,"[{'sentenceNo': 1, 'sentenceContent': ""SK하이닉스가...",NaN
4,4,4,EC_M05_241854,경제,경제일반,"홍남기 \""항만사용료 감면 6개월 더\""…코로나 장기화에 한시조치 줄줄이 연장(상보)",비상경제 중앙대책본부회의,정부가 당초 올해 말까지 시행하려던 항만사용료 및 터미널 임대료 감면조치를 내년 6...,P1,1,A,0,하,13,"[{'sentenceNo': 1, 'sentenceContent': '정부가 당초 ...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482744,53622,53622,SO_M07_920295,사회,사회일반,"경찰 \""수사권 조정안, 추가 후퇴 우려\""…檢·警 수장 국회서 맞붙나",NaN,경찰 내부에서 수사권 조정안 후퇴에 대한 우려가 새어 나오고 있다.\n문무일 검찰총...,P2,1,A,0,하,18,"[{'sentenceNo': 1, 'sentenceContent': '경찰 내부에서...",0.0
482745,53623,53623,SO_M07_920298,사회,전국,제주4.3 추념식 봉행 “특별법 개정…4.3 완전 해결 첫 걸음“,이낙연 총리 “4·3의 진실 채우고 명예를 회복해 드리겠다” 도올 김용옥·배우 유아...,[제주=파이낸셜뉴스] 좌승훈 기자=제71주년 제주4·3 희생자 추념식이 3일 오전 ...,P2,1,A,0,하,11,"[{'sentenceNo': 1, 'sentenceContent': ""[제주=파이낸...",0.0
482746,53624,53624,SO_M07_920301,사회,전국,[전통시장과 함께하는 재래夜 놀자] 밤이 즐거운 서문시장 夜시장,대구 서문시장 야시장 먹거리·볼거리 어우러진 국내 최대 규모 야시장 누적방문객 2천...,"\""대구 서문시장 야시장에서 야(夜)하게 놀자!\"" 지난 2016년 6월 국내 최대...",P2,1,A,0,하,28,"[{'sentenceNo': 1, 'sentenceContent': '\\""대구 서...",0.0
482747,53625,53625,SO_M07_920305,사회,전국,"충남도, 단지·개별형 외국인투자지역 ‘전국 1위’",6곳 142만 8000㎡·19곳 83만 1000㎡…‘외국인 투자 최적지’ 입증,충남도가 단지형과 개별형 외국인투자지역을 전국에서 가장 많이 보유하고 있는 것으로 ...,P2,1,A,0,하,9,"[{'sentenceNo': 1, 'sentenceContent': '충남도가 단지...",0.0
482748,53626,53626,SO_M07_920312,사회,전국,경남 ‘고용위기지역’ 1년 연장..경제 활력 회복 계기 마련,"창원시 진해구·통영시·거제시·고성군, 2020년 4월 4일까지 고용안정 및 일자리사...",지난해 정부로부터 1년간 고용위기지역으로 지정된 경남지역 4개 시군의 고용위기지역 ...,P2,1,A,0,하,9,"[{'sentenceNo': 1, 'sentenceContent': '지난해 정부로...",0.0

In [14]:
df_new = df[['newsTitle','newsSubTitle','newsContent', 'useType','processPattern']]
print(df_new.shape)
print('')
print(df_new.isnull().sum()) # 제목 , 부제목 , 본문 , 낚시 여부 , 처리 패턴(낚시 유형)
df_new.head(3)

(482749, 5)

newsTitle              0
newsSubTitle      335095
newsContent            0
useType                0
processPattern         0
dtype: int64

,newsTitle,newsSubTitle,newsContent,useType,processPattern
0,CCTV 영상으로 핫해진 에스원,"에스원 자체 제작 영상, 유튜브·틱톡 조회수 3500만회 돌파 유튜버들과 협업한 콘...","#. 서울의 한 카페, 아르바이트생이 마감 청소 중 춤을 추고 있다.\n춤 솜씨가 ...",1,0
1,"홈플러스, 신년 '반값, 하나 더 데이' 행사…하루 빠른 31일 시작",NaN,"홈플러스는 새해 첫 쇼핑 축제 '반값, 하나 더 데이' 행사를 경쟁사 대비 하루 빠...",1,0
2,"제주삼다수, 글로벌 품질 인증 갱신",NaN,제주특별자치도개발공사는 제주삼다수의 품질경영표준 ISO9001을 갱신함과 동시에 미...,1,0

In [15]:
df_new['useType'].value_counts() # 낚시x(1) -> 314093개 , 낚시o(0) -> 168656

useType
1    314093
0    168656
Name: count, dtype: int64

In [16]:
df_new['processPattern'].value_counts()

processPattern
0     314093
99    123538
24     19821
23     12233
21      7333
22      5731
Name: count, dtype: int64

#### 낚시성 or 낚시성x

In [22]:
df[df['useType']==1]['partNum'].value_counts() # 낚시 아닌것은 균등하게 분포

partNum
P2    163509
P1    150584
Name: count, dtype: int64

In [23]:
df[df['useType']==0]['partNum'].value_counts() # 특이하게 낚시 인것들은 본문 도메인 일관성 부족만 있음

partNum
P2    168656
Name: count, dtype: int64

In [17]:
df['partNum'].value_counts() # p1(제목 본문 불일치=150000) , p2(본문 도메인 일관성 부족=330000)

partNum
P2    332165
P1    150584
Name: count, dtype: int64

In [26]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'newsID', 'newsCategory',
       'newsSubcategory', 'newsTitle', 'newsSubTitle', 'newsContent',
       'partNum', 'useType', 'processType', 'processPattern', 'processLevel',
       'sentenceCount', 'sentenceInfo', 'processSentencenum'],
      dtype='object')

In [29]:
d_c = pd.read_csv('concat.csv')
d_c.head(5)

,Unnamed: 0.1,Unnamed: 0,newsID,newsCategory,newsSubcategory,newsTitle,newsSubTitle,newsContent,partNum,useType,processType,processPattern,processLevel,sentenceCount,sentenceInfo
0,0,0,EC_M02_000001,경제,일반,"[오늘의 SR이슈] 윤리 문제 불거진 종근당 회장 조사 마치고 귀가…\""사죄한다\""",NaN,"\""사죄한다.\"" 운전기사들에게 허구한 날 폭언을 퍼부어 윤리 문제가 불거진 이장한...",P1,0,A,99,하,9,"[{'sentenceNo': 1, 'sentenceContent': '\\""사죄한다..."
1,1,1,EC_M02_000005,경제,은행,"최종구 금융위원장, 임팩트금융 정착 위해 정부 차원 기금 조성",NaN,"최종구 금융위원회 위원장이 \""'임팩트금융(사회적금융)'의 안착 차원에서 정부가 직...",P1,0,A,99,하,13,"[{'sentenceNo': 1, 'sentenceContent': '최종구 금융위..."
2,2,2,EC_M02_000006,경제,은행,한국기업지배구조원 733개 기업 ESG 등급 부여,NaN,"한국기업지배구조원이 8월 31일 국내 상장회사의 환경경영(E), 사회책임경영(S),...",P1,0,A,99,하,13,"[{'sentenceNo': 1, 'sentenceContent': '한국기업지배구..."
3,3,3,EC_M02_000007,경제,산업,가을 맞아 더 활발한 기업 프로보노 활동,NaN,요즘 프로보노 형 사회 공헌 활동을 펴는 회사가 늘고 있다.\n회사를 경영하거나 기...,P1,0,A,99,하,13,"[{'sentenceNo': 1, 'sentenceContent': '요즘 프로보노..."
4,4,4,EC_M02_000008,경제,일반,2017 다우존스 지속가능경영지수 어떤 기업이 편입되었나?,NaN,"런던 현지 시각으로 7일, 스탠다드앤푸어스 다우존스 인디시즈와 로베코샘이 다우존스지...",P1,0,A,99,하,9,"[{'sentenceNo': 1, 'sentenceContent': '런던 현지 시..."

In [37]:
df = df[['newsID', 'newsCategory',
        'newsSubcategory', 'newsTitle', 'newsSubTitle', 'newsContent',
        'partNum', 'useType', 'processType', 'processPattern', 'processLevel',
        'sentenceCount', 'sentenceInfo']]
d_c = d_c[['newsID', 'newsCategory',
        'newsSubcategory', 'newsTitle', 'newsSubTitle', 'newsContent',
        'partNum', 'useType', 'processType', 'processPattern', 'processLevel',
        'sentenceCount', 'sentenceInfo']]

In [38]:
df_final = pd.concat([df,d_c])

In [41]:
df_final[df_final['useType']==1]['partNum'].value_counts()

partNum
P2    168656
P1    164370
Name: count, dtype: int64

In [42]:
df_final[df_final['useType']==0]['partNum'].value_counts()

partNum
P2    168656
P1    164370
Name: count, dtype: int64

In [45]:
df_final.to_csv('df_final.csv')

In [47]:
pd.read_csv('df_final.csv')

,Unnamed: 0,newsID,newsCategory,newsSubcategory,newsTitle,newsSubTitle,newsContent,partNum,useType,processType,processPattern,processLevel,sentenceCount,sentenceInfo
0,0,EC_M05_241847,경제,중기밴처,CCTV 영상으로 핫해진 에스원,"에스원 자체 제작 영상, 유튜브·틱톡 조회수 3500만회 돌파 유튜버들과 협업한 콘...","#. 서울의 한 카페, 아르바이트생이 마감 청소 중 춤을 추고 있다.\n춤 솜씨가 ...",P1,1,A,0,하,15,"[{'sentenceNo': 1, 'sentenceContent': '#. 서울의 ..."
1,1,EC_M05_241848,경제,유통,"홈플러스, 신년 '반값, 하나 더 데이' 행사…하루 빠른 31일 시작",NaN,"홈플러스는 새해 첫 쇼핑 축제 '반값, 하나 더 데이' 행사를 경쟁사 대비 하루 빠...",P1,1,A,0,하,8,"[{'sentenceNo': 1, 'sentenceContent': ""홈플러스는 새..."
2,2,EC_M05_241851,경제,유통,"제주삼다수, 글로벌 품질 인증 갱신",NaN,제주특별자치도개발공사는 제주삼다수의 품질경영표준 ISO9001을 갱신함과 동시에 미...,P1,1,A,0,하,6,"[{'sentenceNo': 1, 'sentenceContent': '제주특별자치도..."
3,3,EC_M05_241852,경제,기업CEO,"SK하이닉스, 인텔 낸드 인수 1단계 완료…美자회사 이름은 '솔리다임'",NaN,SK하이닉스가 미국 인텔의 낸드플래시 사업부 인수 1단계 절차를 완료하고 인텔 SS...,P1,1,A,0,하,13,"[{'sentenceNo': 1, 'sentenceContent': ""SK하이닉스가..."
4,4,EC_M05_241854,경제,경제일반,"홍남기 \""항만사용료 감면 6개월 더\""…코로나 장기화에 한시조치 줄줄이 연장(상보)",비상경제 중앙대책본부회의,정부가 당초 올해 말까지 시행하려던 항만사용료 및 터미널 임대료 감면조치를 내년 6...,P1,1,A,0,하,13,"[{'sentenceNo': 1, 'sentenceContent': '정부가 당초 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647114,164365,SO_M06_219096,사회,"사회,법조,법조",25년 산통 끝 공수처 출범…처장 집중 권력에 ‘옥상옥’ 우려도,"\""검찰총장은 법무장관이 견제...공수처장은 없다\""",1996년 이후 추진과 무산이 반복되는 25년 산고 끝에 고위공직자범죄수사처(공수처...,P1,0,D,12,하,26,"[{'sentenceNo': 1, 'sentenceContent': '1996년 이..."
647115,164366,SO_M06_219097,사회,"사회,사회일반,사회일반",北대사 대리 잇단 탈북...이유는,외화벌이 금지 등 대북제재 강화에 추방 잇따라이탈리아 이어 쿠웨이트 대사대리도 국내...,북한 조성길 전 주이탈리아 대사대리에 이어 전 주쿠웨이트 대사대리도 한국에 입국한 ...,P1,0,D,12,하,19,"[{'sentenceNo': 1, 'sentenceContent': '북한 조성길 ..."
647116,164367,SO_M06_219103,사회,"사회,법조,법조","[단독] 靑청원서 폭로한 기획부동산 실체…\""구인광고로 상담원 모아 피라미드식 판매...","<중>수렁에 빠진 땅 매수자들▶사기 수법은실적 못내면 압박, 직원들 노려","“기획부동산이 서민들의 피 같은 생활자금과 여유자금, 종자돈을 투자하게 해 막대한 ...",P1,0,D,12,하,17,"[{'sentenceNo': 1, 'sentenceContent': '“기획부동산이..."
647117,164368,SO_M06_219105,사회,"사회,사회일반,사회일반","경찰, '김종철 성추행' 수사 착수…장혜영 반발에 활빈단 \""성추행 고발 뭐가 문제냐\""","경찰, 시민단체가 고발한 '김종철 성추행 사건' 수사 착수\""친고죄 폐지는 피해자 ...",경찰이 김종철 전 정의당 대표에 대한 시민단체들의 성추행 고발 사건 수사에 착수했다...,P1,0,D,12,하,13,"[{'sentenceNo': 1, 'sentenceContent': '경찰이 김종철..."
647118,164369,SO_M06_219123,사회,"사회,사회일반,사회일반","\""1,200만원 줄게\"" 미성년자 2명과 성관계한 30대 징역 3년6개월",NaN,창원지법 형사4부(이헌 부장판사)는 큰돈을 주겠다며 미성년자들에게 접근해 성관계를 ...,P1,0,D,12,하,7,"[{'sentenceNo': 1, 'sentenceContent': '창원지법 형사..."